package ch.idsia.adaptive.backend.services.templates;

/**
 * Author:  Claudio "Dna" Bonesana
 * Project: adapquest
 * Date:    03.11.2021 15:35
 */
public interface Settings {

	String ACCESS_CODE = "ACCESS_CODE";
	String LANGUAGE = "LANGUAGE";
	String SURVEY_DESCRIPTION = "SURVEY_DESCRIPTION";
	String DURATION = "DURATION";
	String MIXED_SKILL_ORDER = "MIXED_SKILL_ORDER";
	String ADAPTIVE = "ADAPTIVE";
	String SIMPLE = "SIMPLE";
	String STRUCTURAL = "STRUCTURAL";
	String NO_SKILL = "NO_SKILL";
	String RANDOM_QUESTIONS = "RANDOM_QUESTIONS";
	String QUESTION_PER_SKILL_MIN = "QUESTION_PER_SKILL_MIN";
	String QUESTION_PER_SKILL_MAX = "QUESTION_PER_SKILL_MAX";
	String QUESTION_TOTAL_MIN = "QUESTION_TOTAL_MIN";
	String QUESTION_TOTAL_MAX = "QUESTION_TOTAL_MAX";
	String SCORE_LOWER_THRESHOLD = "SCORE_LOWER_THRESHOLD";
	String SCORE_UPPER_THRESHOLD = "SCORE_UPPER_THRESHOLD";
	String GLOBAL_MEAN_SCORE_UPPER_THRESHOLD = "GLOBAL_MEAN_SCORE_UPPER_THRESHOLD";
	String GLOBAL_MEAN_SCORE_LOWER_THRESHOLD = "GLOBAL_MEAN_SCORE_LOWER_THRESHOLD";

}
