version: '3.3'

services:

  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: "ada"
      POSTGRES_PASSWORD: "ada"
      POSTGRES_DB: "adaptive"
    restart: unless-stopped
    ports:
      - "5432:5432"

  backend:
    image: ch.idsia.adaptive:latest
    build:
      context: .
    environment:
      MAGIC_API_KEY: "QWRhcHRpdmUgU3VydmV5"

      DB_DBMS: "postgresql"
      DB_HOSTNAME: "db"
      DB_PORT: "5432"
      DB_SCHEMA: "adaptive"
      DB_USERNAME: "ada"
      DB_PASSWORD: "ada"

      ADAPQUEST_CONTROLLER_ASSISTANT: "false"
      ADAPQUEST_CONTROLLER_CONSOLE: "false"
      ADAPQUEST_CONTROLLER_DASHBOARD: "false"
      ADAPQUEST_CONTROLLER_DEMO: "true"
      ADAPQUEST_CONTROLLER_EXPERIMENTS: "false"
      ADAPQUEST_CONTROLLER_LIVE: "false"

      SPRING_PROFILE_ACTIVE: "demo"

      ADAPQUEST_PAGE_TITLE: "AdapQuest"

      ADAPQUEST_EXIT_URL: "" # not used if empty
      ADAPQUEST_EXIT_TEXT: "" # not used if empty

      ADAPQUEST_KEYCLOAK_ROLE: "user" # not used if empty
      ADAPQUEST_KEYCLOAK_ADMIN: "admin" # used only with console

      ADAPQUEST_KEYCLOAK_FIELD: "email"

      KEYCLOAK_ENABLED: "true"
      KEYCLOAK_REALM: "<realm>"
      KEYCLOAK_AUTH_SERVER_URL: "<url>"
      KEYCLOAK_RESOURCE: "<client-id>"
      KEYCLOAK_CREDENTIALS_SECRET: "<secret>"

    restart: unless-stopped
    ports:
      - "8080:8080"
