version: '3.3'

services:

  db:
    image: postgres:13.1
    environment:
      POSTGRES_USER: "ada"
      POSTGRES_PASSWORD: "ada"
      POSTGRES_DB: "adaptive"
    restart: unless-stopped
    ports:
      - "5432:5432"

  backend:
    image: ch.idsia.adaptive:latest
    build:
      context: .
    environment:
      MAGIC_API_KEY: "QWRhcHRpdmUgU3VydmV5"
      DB_DBMS: "postgresql"
      DB_HOSTNAME: "db"
      DB_PORT: "5432"
      DB_SCHEMA: "adaptive"
      DB_USERNAME: "ada"
      DB_PASSWORD: "ada"
    restart: unless-stopped
    ports:
      - "8080:8080"
