adapquest:
  controller:
    assistant: false
    console: true
    dashboard: false
    demo: false
    experiments: false

logging:
  level:
    ch.idsia: warn
    ch.idsia.adaptive.backend.services:
      templates: warn
      InitializationService: warn
    org.apache.catalina: warn
    org.springframework: warn
    org.hibernate: warn
