adapquest:
  controller:
    assistant: false
    console: false
    dashboard: false
    demo: true
    experiments: false

logging:
  level:
    ch.idsia: info
    ch.idsia.adaptive.backend.services:
      templates: warn
      InitializationService: warn
    org.apache.catalina: warn
    org.springframework: warn
    org.hibernate: warn
